<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ttt_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for the Tic-Tac-Toe final project stack</description>
  <maintainer email="xingxin.he@connect.ust.hk">ISDN3000E TA</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_resources_panda_moveit_config</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>ttt_engine</exec_depend>
  <exec_depend>ttt_dummy</exec_depend>
  <exec_depend>ttt_hidden</exec_depend>
  <exec_depend>ttt_layout</exec_depend>
  <exec_depend>ttt_player</exec_depend>
  <exec_depend>ttt_referee</exec_depend>
  <exec_depend>ttt_visualizer</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
